// The 14 CRediT contributor roles as 14x14 pixel icons, in the taxonomy's
// order. Each role gets its own silhouette and its own main colour so they
// stay easy to tell apart at a glance. Loaded after pixel.js.

const ROLE_INK = '#1f2440';

const ROLE_ICONS = [
    {
        name: 'CONCEPTUALIZATION', color: '#ffd23f',
        pal: { y: '#fff3a6', Y: '#ffd23f', o: '#f0a020', G: '#b8c0cc', g: '#7c8699' },
        rows: [
            '....KKKKKK....',
            '...KyyYYYYK...',
            '..KyyYYYYYYK..',
            '..KyYYYYYYoK..',
            '..KYYYYYYYoK..',
            '..KYYYYYYooK..',
            '...KYYYYYoK...',
            '....KYYYoK....',
            '....KGGGGK....',
            '....KggggK....',
            '....KGGGGK....',
            '.....KggK.....',
            '......KK......',
            '..............',
        ],
    },
    {
        name: 'DATA CURATION', color: '#4c8dff',
        pal: { L: '#bcd6ff', B: '#4c8dff', b: '#2f5fd0' },
        rows: [
            '...KKKKKKKK...',
            '..KLLLLLLLLK..',
            '.KBLLLLLLLLBK.',
            '.KbBBBBBBBBbK.',
            '.KBbbbbbbbbBK.',
            '.KBBBBBBBBBBK.',
            '.KbBBBBBBBBbK.',
            '.KBbbbbbbbbBK.',
            '.KBBBBBBBBBBK.',
            '.KbBBBBBBBBbK.',
            '.KBbbbbbbbbBK.',
            '..KBBBBBBBBK..',
            '...KKKKKKKK...',
            '..............',
        ],
    },
    {
        name: 'FORMAL ANALYSIS', color: '#27c3a4',
        pal: { L: '#8ff0d8', G: '#27c3a4' },
        rows: [
            '..............',
            '.........KKKK.',
            '.........KLGK.',
            '.........KLGK.',
            '.....KKKKKLGK.',
            '.....KLGKKLGK.',
            '.....KLGKKLGK.',
            '.KKKKKLGKKLGK.',
            '.KLGKKLGKKLGK.',
            '.KLGKKLGKKLGK.',
            '.KLGKKLGKKLGK.',
            '.KLGKKLGKKLGK.',
            'KKKKKKKKKKKKKK',
            '..............',
        ],
    },
    {
        name: 'FUNDING ACQUISITION', color: '#e8b86a',
        pal: { T: '#f2c98a', t: '#c9914a', D: '#2e8f3e' },
        rows: [
            '.....KKKK.....',
            '....KTTTTK....',
            '.....KtTK.....',
            '....KKKKKK....',
            '...KTTTDTTK...',
            '..KTTTDDDDTK..',
            '.KTTTDTDTTTtK.',
            '.KTTTTDDDTTtK.',
            '.KTTTTTDTDTtK.',
            '.KTTTDDDDTTtK.',
            '.KTTTTTDTTTtK.',
            '..KTTTTTTTtK..',
            '...KKKKKKKK...',
            '..............',
        ],
    },
    {
        name: 'INVESTIGATION', color: '#5fb8f0',
        pal: { S: '#c8d0dc', L: '#c9ecff', l: '#7fc4f0', W: '#ffffff', H: '#9a6232', h: '#5a3418' },
        rows: [
            '...KKKKK......',
            '..KSSSSSK.....',
            '.KSLLLLLSK....',
            'KSLWWLLLlSK...',
            'KSLWLLLLlSK...',
            'KSLLLLLLlSK...',
            'KSLLLLLllSK...',
            'KSLLLLlllSK...',
            '.KSlllllSKK...',
            '..KSSSSSKHHK..',
            '...KKKKKKHhHK.',
            '.........KHhHK',
            '..........KHhK',
            '...........KK.',
        ],
    },
    {
        name: 'METHODOLOGY', color: '#9b6bff',
        pal: { C: '#b8843a', G: '#eef6ff', w: '#ffffff', P: '#9b6bff', p: '#6a44c8' },
        rows: [
            '.....KKKK.....',
            '.....KCCK.....',
            '....KKKKKK....',
            '.....KGGK.....',
            '.....KGGK.....',
            '.....KGGK.....',
            '....KGGGGK....',
            '...KGGwGGGK...',
            '..KPPPPPPPPK..',
            '.KPPwPPPPPpPK.',
            '.KPPPPPwPPpPK.',
            'KPPPPPPPPPPpPK',
            'KKKKKKKKKKKKKK',
            '..............',
        ],
    },
    {
        name: 'PROJECT ADMINISTRATION', color: '#c98a4a',
        pal: { B: '#c98a4a', b: '#8a5a2b', M: '#b8c0cc', W: '#ffffff', C: '#22c07a', E: '#dde3ea', L: '#9aa6b8' },
        rows: [
            '.....KKKK.....',
            '...KKKMMKKK...',
            '.KKBKMMMMKBKK.',
            '.KBBKKKKKKBBK.',
            '.KBWWWWWWWWBK.',
            '.KBWCCWLLLWBK.',
            '.KBWCCWWWWWBK.',
            '.KBWWWWWWWWBK.',
            '.KBWCCWLLLWBK.',
            '.KBWCCWWWWWBK.',
            '.KBWWWWWWWWBK.',
            '.KBWEEWLLWWBK.',
            '.KbBBBBBBBBbK.',
            '.KKKKKKKKKKKK.',
        ],
    },
    {
        name: 'RESOURCES', color: '#ff9a4a',
        pal: { O: '#ffc27a', o: '#f0964a', d: '#b8662a', T: '#fff0d0', L: '#fff8ec' },
        rows: [
            '..KKKKKKKKKK..',
            '.KOOOOTTOOOOK.',
            'KOOOOOTTOOOOOK',
            'KKKKKKKKKKKKKK',
            'KooooKTTKooodK',
            'KooooKTTKooodK',
            'KooooKKKKooodK',
            'KooooooooooodK',
            'KoLLLooooooodK',
            'KoLLLooooooodK',
            'KooooooooooodK',
            'KddddddddddddK',
            'KKKKKKKKKKKKKK',
            '..............',
        ],
    },
    {
        name: 'SOFTWARE', color: '#3ddc84',
        pal: { F: '#c8d0dc', f: '#8a94a8', S: '#1f2a44', G: '#3ddc84', C: '#5fd0ff' },
        rows: [
            'KKKKKKKKKKKKKK',
            'KFFFFFFFFFFFFK',
            'KFSSSSSSSSSSFK',
            'KFSGGSCCCSSSFK',
            'KFSSSGGGSSSSFK',
            'KFSSSGGCCCSSFK',
            'KFSGGSSSSSSSFK',
            'KFSSSSSSSSSSFK',
            'KFFFFFFFFFFFFK',
            'KKKKKKKKKKKKKK',
            '.....KffK.....',
            '.....KffK.....',
            '...KKKKKKKK...',
            '..............',
        ],
    },
    {
        name: 'SUPERVISION', color: '#17b3d6',
        pal: { H: '#4a2f1f', S: '#ffd6ae', T: '#17b3d6', t: '#0f7f9a', Y: '#ffd23f' },
        rows: [
            '...........K..',
            '...KKKK...KYK.',
            '..KHHHHK.KYYYK',
            '.KHHHHHHK.KYK.',
            '.KHSSSSHK..K..',
            '.KSKSSKSK.....',
            '..KSSSSK......',
            '...KSSK.......',
            '.KKTTTTKK.....',
            'KTTTTTTTTK....',
            'KTTTtTTTTK....',
            'KTTTtTTTTK....',
            'KTTTtTTTTK....',
            'KKKKKKKKKK....',
        ],
    },
    {
        name: 'VALIDATION', color: '#22c07a',
        pal: { L: '#8ff0b8', G: '#22c07a', g: '#15905a', W: '#ffffff' },
        rows: [
            '.KKKKKKKKKKKK.',
            '.KLLLLLLLLLgK.',
            '.KLGGGGGGGGgK.',
            '.KLGGGGGGGWgK.',
            '.KLGGGGGGWWgK.',
            '.KLGWGGGWWGgK.',
            '.KLGWWGWWGGgK.',
            '.KLGGWWWGGGgK.',
            '..KLGGWGGGgK..',
            '..KLGGGGGGgK..',
            '...KLGGGGgK...',
            '....KLGGgK....',
            '.....KKKK.....',
            '..............',
        ],
    },
    {
        name: 'VISUALIZATION', color: '#ff5d8f',
        pal: { R: '#ff5d8f', Y: '#ffd23f', B: '#4c8dff' },
        rows: [
            '....KKKKKK....',
            '..KKRRRRYYKK..',
            '.KRRRRRRYYYYK.',
            '.KRRRRRRYYYYK.',
            'KRRRRRRRYYYYYK',
            'KRRRRRRRYYYYYK',
            'KRRRRRRRKKKKKK',
            'KRRRRRRBBBBBBK',
            'KRRRRRBBBBBBBK',
            '.KRRRBBBBBBBK.',
            '.KRRBBBBBBBBK.',
            '..KKBBBBBBKK..',
            '....KKKKKK....',
            '..............',
        ],
    },
    {
        name: 'WRITING - ORIGINAL DRAFT', color: '#ffb020',
        pal: { P: '#ff8fb1', M: '#c8d0dc', Y: '#ffd23f', y: '#e0a820', W: '#f4d9a8', G: '#3a3a44' },
        rows: [
            '...........KK.',
            '..........KPPK',
            '.........KMPPK',
            '........KYMMK.',
            '.......KYYyK..',
            '......KYYyK...',
            '.....KYYyK....',
            '....KYYyK.....',
            '...KYYyK......',
            '..KWWyK.......',
            '.KGWWK........',
            '.KGGK.........',
            'KKKK..........',
            '..............',
        ],
    },
    {
        name: 'WRITING - REVIEW & EDITING', color: '#e2413b',
        pal: { W: '#ffffff', F: '#dde3ea', L: '#9aa6b8', R: '#e2413b' },
        rows: [
            '.KKKKKKKKK....',
            '.KWWWWWWWFK...',
            '.KWLLLLLWFFK..',
            '.KWWWWWWWKKKK.',
            '.KWLLLLLLLLWK.',
            '.KWWWWWWWWWWK.',
            '.KWRRRRRRRRWK.',
            '.KWWWWWWWWWWK.',
            '.KWLLLLWWWWRK.',
            '.KWWWWWWWWRWK.',
            '.KWLLLWRWRWWK.',
            '.KWWWWWWRWWWK.',
            '.KKKKKKKKKKKK.',
            '..............',
        ],
    },
];

// draws role i with its top-left at (x, y); ink swaps the outline colour
function roleIcon(p, i, x, y, { scale = 1, ink = ROLE_INK } = {}) {
    const { rows, pal } = ROLE_ICONS[i];
    p.sprite(rows, { ...pal, K: ink }, x, y, { scale });
}
